# Generated by Django 3.0.6 on 2020-06-21 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='complate',
            new_name='complete',
        ),
    ]
